apiVersion: apps/v1
kind: Deployment
metadata:
  name: caden-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caden-api
  template:
    metadata:
      labels:
        app: caden-api
    spec:
      containers:
        - name: caden-api
        # This image is going to be the path to the image you create in a future step
          image: us-docker.pkg.dev/cit262-team1-project/caden-api/api-tests:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 10